(define (problem complex-rearrange)
  (:domain blocksworld-4ops)
  (:objects A B C D - block)
  (:init (arm-empty)
         (on-table A) (on B A) (clear B)
         (on-table C) (on D C) (clear D))
  (:goal (and (on A B) (on B C) (on C D) (on-table D))))